# Generated by Django 5.0.14 on 2025-09-19 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="Полное имя сотрудника.",
                        max_length=255,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("AUDITOR", "Аудитор"), ("ADMIN", "Администратор")],
                        default="AUDITOR",
                        help_text="Определяет доступ к административным разделам.",
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Контактный номер для связи.",
                        max_length=32,
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Внутренний идентификатор сотрудника.",
                        max_length=64,
                        verbose_name="Табельный номер",
                    ),
                ),
                (
                    "password_changed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Когда пользователь в последний раз менял пароль.",
                        null=True,
                        verbose_name="Дата смены пароля",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
    ]
