# Generated by Django 5.0.14 on 2025-09-21 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        choices=[("building", "Здания"), ("elevator", "Лифты")],
                        max_length=20,
                        verbose_name="Справочник",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Ошибка")],
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Имя файла"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата запуска"
                    ),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(default=0, verbose_name="Всего строк"),
                ),
                (
                    "created_count",
                    models.PositiveIntegerField(default=0, verbose_name="Создано"),
                ),
                (
                    "updated_count",
                    models.PositiveIntegerField(default=0, verbose_name="Обновлено"),
                ),
                (
                    "error_rows",
                    models.JSONField(blank=True, default=list, verbose_name="Ошибки"),
                ),
                ("message", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catalog_imports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Инициатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал импорта справочников",
                "verbose_name_plural": "Журналы импорта справочников",
                "ordering": ["-created_at"],
            },
        ),
    ]
