# Generated by Django 5.0.14 on 2025-09-20 22:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Отображаемое имя чек-листа.",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительные инструкции или область применения.",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Дата, когда чек-лист стал доступен для назначения аудитов.",
                        null=True,
                        verbose_name="Опубликован",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Флаг, разрешающий использовать шаблон для новых аудитов.",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Чек-лист",
                "verbose_name_plural": "Чек-листы",
                "ordering": ["-published_at", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Используется для сортировки вопросов.",
                        verbose_name="Порядок",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        help_text="Логическая зона или раздел обследования.",
                        max_length=100,
                        verbose_name="Зона",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Категория или тематическая группа.",
                        max_length=100,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        help_text="Текст вопроса, отображаемый аудитору.",
                        verbose_name="Формулировка",
                    ),
                ),
                (
                    "help_text",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительные инструкции для аудитора.",
                        verbose_name="Подсказка",
                    ),
                ),
                (
                    "score_type",
                    models.CharField(
                        choices=[
                            ("numeric", "Числовая шкала"),
                            ("option", "Выбор варианта"),
                        ],
                        default="numeric",
                        max_length=20,
                        verbose_name="Тип оценки",
                    ),
                ),
                (
                    "min_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Минимальный балл",
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Максимальный балл",
                    ),
                ),
                (
                    "step",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="Шаг",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Возможные варианты ответа для выбора.",
                        verbose_name="Варианты",
                    ),
                ),
                (
                    "requires_comment",
                    models.BooleanField(
                        default=False, verbose_name="Комментарий обязателен"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        help_text="Множитель при расчёте итогового балла.",
                        max_digits=6,
                        verbose_name="Вес",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="checklists.checklisttemplate",
                        verbose_name="Чек-лист",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт чек-листа",
                "verbose_name_plural": "Пункты чек-листа",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="checklistitem",
            constraint=models.UniqueConstraint(
                fields=("template", "order"), name="unique_order_per_template"
            ),
        ),
    ]
