# Generated by Django 5.0.14 on 2025-09-19 18:25

import audits.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "catalog",
            "0002_checklistcategory_checklistsection_checklistquestion_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_info",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Снимок пользовательских полей объекта на момент проверки.",
                        verbose_name="Информационная карта",
                    ),
                ),
                (
                    "planned_date",
                    models.DateField(
                        blank=True,
                        help_text="Дата, на которую была запланирована проверка.",
                        null=True,
                        verbose_name="Плановая дата",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Фактическое время начала аудита.",
                        null=True,
                        verbose_name="Начато",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Фактическое время завершения аудита.",
                        null=True,
                        verbose_name="Завершено",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("in_progress", "В работе"),
                            ("submitted", "Отправлен"),
                            ("reviewed", "Просмотрен"),
                        ],
                        default="draft",
                        help_text="Жизненный цикл аудита.",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Когда аудит был создан.",
                        verbose_name="Создан",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Когда запись аудита последний раз изменялась.",
                        verbose_name="Обновлён",
                    ),
                ),
                (
                    "total_score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Агрегированная сумма баллов по ответам.",
                        verbose_name="Суммарный балл",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Пользователь, инициировавший аудит.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
                (
                    "elevator",
                    models.ForeignKey(
                        help_text="Объект проверки.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits",
                        to="catalog.elevator",
                        verbose_name="Лифт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аудит",
                "verbose_name_plural": "Аудиты",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AuditResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        help_text="Выбранный балл или значение для вопроса.",
                        null=True,
                        verbose_name="Баллы",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Пояснение аудитора.",
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "is_flagged",
                    models.BooleanField(
                        default=False,
                        help_text="Дополнительная пометка для администратора.",
                        verbose_name="Требует внимания",
                    ),
                ),
                (
                    "is_offline_cached",
                    models.BooleanField(
                        default=False,
                        help_text="Отмечает ответы, пришедшие из офлайн-синхронизации.",
                        verbose_name="Получен офлайн",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Когда ответ был сохранён впервые.",
                        verbose_name="Создан",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Когда ответ последний раз изменялся.",
                        verbose_name="Обновлён",
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        help_text="Проверка, к которой относится ответ.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="audits.audit",
                        verbose_name="Аудит",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Позиция чек-листа.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_responses",
                        to="catalog.checklistquestion",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ аудита",
                "verbose_name_plural": "Ответы аудита",
            },
        ),
        migrations.CreateModel(
            name="AuditAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        help_text="Вложение с подтверждающими материалами.",
                        upload_to=audits.models.attachment_upload_to,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Краткое пояснение к вложению.",
                        max_length=255,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "offline_uuid",
                    models.UUIDField(
                        blank=True,
                        help_text="Временный идентификатор до синхронизации.",
                        null=True,
                        unique=True,
                        verbose_name="Offline UUID",
                    ),
                ),
                (
                    "stored_size",
                    models.PositiveIntegerField(
                        editable=False,
                        help_text="Фактический размер вложения.",
                        verbose_name="Размер файла, байт",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Когда файл был загружен.",
                        verbose_name="Загружено",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        help_text="Ответ, к которому прикреплён файл.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="audits.auditresponse",
                        verbose_name="Ответ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение аудита",
                "verbose_name_plural": "Вложения аудита",
            },
        ),
        migrations.CreateModel(
            name="AuditSignature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signed_by",
                    models.CharField(
                        help_text="ФИО или должность лица, подтвердившего аудит.",
                        max_length=255,
                        verbose_name="Подписант",
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        help_text="Изображение подписи.",
                        upload_to=audits.models.signature_upload_to,
                        verbose_name="Подпись",
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Когда была оставлена подпись.",
                        verbose_name="Дата подписи",
                    ),
                ),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signature",
                        to="audits.audit",
                        verbose_name="Аудит",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подпись аудита",
                "verbose_name_plural": "Подписи аудита",
            },
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(fields=["status"], name="audits_audi_status_2432b1_idx"),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(
                fields=["created_at"], name="audits_audi_created_62d5af_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="auditresponse",
            constraint=models.UniqueConstraint(
                fields=("audit", "question"), name="unique_question_per_audit"
            ),
        ),
        migrations.AddIndex(
            model_name="auditattachment",
            index=models.Index(
                fields=["uploaded_at"], name="audits_audi_uploade_641a42_idx"
            ),
        ),
    ]
