# Generated by Django 5.0.14 on 2025-09-19 19:06

import audits.models
import audits.storages
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditattachment",
            name="file",
            field=models.ImageField(
                help_text="Вложение с подтверждающими материалами.",
                storage=audits.storages._ProtectedFileSystemStorage(),
                upload_to=audits.models.attachment_upload_to,
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="auditsignature",
            name="signature_image",
            field=models.ImageField(
                help_text="Изображение подписи.",
                storage=audits.storages._ProtectedFileSystemStorage(),
                upload_to=audits.models.signature_upload_to,
                verbose_name="Подпись",
            ),
        ),
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("audit.created", "Аудит создан"),
                            ("audit.status_changed", "Статус аудита изменён"),
                            ("response.created", "Ответ добавлен"),
                            ("response.updated", "Ответ обновлён"),
                            ("response.deleted", "Ответ удалён"),
                            ("attachment.created", "Вложение добавлено"),
                            ("attachment.updated", "Вложение обновлено"),
                            ("attachment.deleted", "Вложение удалено"),
                            ("signature.created", "Подпись добавлена"),
                            ("signature.updated", "Подпись обновлена"),
                            ("signature.deleted", "Подпись удалена"),
                        ],
                        help_text="Тип события.",
                        max_length=50,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Полное имя модели, к которой относится событие.",
                        max_length=100,
                        verbose_name="Тип сущности",
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True,
                        help_text="Первичный ключ записи или временный идентификатор.",
                        max_length=64,
                        verbose_name="Идентификатор сущности",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Дополнительная информация о событии.",
                        verbose_name="Данные",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Время фиксации события.",
                        verbose_name="Создано",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Кто инициировал действие.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_log_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись журнала аудита",
                "verbose_name_plural": "Журнал аудита",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audits_audi_entity__3b3cd2_idx",
                    ),
                    models.Index(
                        fields=["action"], name="audits_audi_action_5ca229_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="audits_audi_created_262fbf_idx"
                    ),
                ],
            },
        ),
    ]
