# Generated by Django 5.0.14 on 2025-09-19 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0002_alter_auditattachment_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineSyncBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Идентификатор устройства, выполнившего синхронизацию.",
                        max_length=255,
                        verbose_name="Устройство",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Содержимое запроса на синхронизацию.",
                        verbose_name="Данные",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В обработке"),
                            ("applied", "Применён"),
                            ("error", "Ошибка"),
                        ],
                        default="pending",
                        help_text="Результат обработки пакета.",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "error_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Описание ошибок, если обработка завершилась неудачно.",
                        verbose_name="Сведения об ошибке",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Когда пакет был принят сервером.",
                        verbose_name="Создано",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Кто инициировал синхронизацию.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offline_batches",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пакет офлайн-синхронизации",
                "verbose_name_plural": "Пакеты офлайн-синхронизации",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="audits_offl_status_adadde_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="audits_offl_created_e6df8e_idx"
                    ),
                ],
            },
        ),
    ]
