# Generated by Django 5.0.14 on 2025-09-19 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0003_offlinesyncbatch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="offlinesyncbatch",
            name="payload_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Детерминированный отпечаток исходного запроса.",
                max_length=64,
                verbose_name="Хэш данных",
            ),
        ),
        migrations.AddField(
            model_name="offlinesyncbatch",
            name="response_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Снимок ответа, возвращённого клиенту.",
                verbose_name="Ответ",
            ),
        ),
        migrations.AddField(
            model_name="offlinesyncbatch",
            name="response_status",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="HTTP-статус ответа на запрос синхронизации.",
                verbose_name="Код ответа",
            ),
        ),
        migrations.AddIndex(
            model_name="offlinesyncbatch",
            index=models.Index(
                fields=["payload_hash"], name="audits_offl_payload_2b1951_idx"
            ),
        ),
    ]
