# Generated by Django 5.0.14 on 2025-09-20 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0004_offlinesyncbatch_payload_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentLimitConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="default",
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Ключ",
                    ),
                ),
                (
                    "max_size_mb",
                    models.PositiveIntegerField(
                        default=8,
                        help_text="Применяется к каждому вложению.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Максимальный размер файла (МБ)",
                    ),
                ),
                (
                    "max_per_response",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Сколько вложений допустимо прикрепить к одному вопросу чек-листа.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Файлов на ответ",
                    ),
                ),
                (
                    "max_per_audit",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Совокупный лимит вложений в рамках одного аудита.",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Файлов на аудит",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Настройка вложений аудита",
                "verbose_name_plural": "Настройки вложений аудита",
            },
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="action",
            field=models.CharField(
                choices=[
                    ("audit.created", "Аудит создан"),
                    ("audit.status_changed", "Статус аудита изменён"),
                    ("audit.changes_requested", "Запрошены правки по аудиту"),
                    ("response.created", "Ответ добавлен"),
                    ("response.updated", "Ответ обновлён"),
                    ("response.deleted", "Ответ удалён"),
                    ("attachment.created", "Вложение добавлено"),
                    ("attachment.updated", "Вложение обновлено"),
                    ("attachment.deleted", "Вложение удалено"),
                    ("signature.created", "Подпись добавлена"),
                    ("signature.updated", "Подпись обновлена"),
                    ("signature.deleted", "Подпись удалена"),
                    ("audit.reviewed", "Аудит просмотрен"),
                    ("offline.batch_created", "Офлайн-пакет принят"),
                    ("offline.batch_applied", "Офлайн-пакет применён"),
                    ("offline.batch_error", "Ошибка офлайн-пакета"),
                ],
                help_text="Тип события.",
                max_length=50,
                verbose_name="Действие",
            ),
        ),
    ]
