# Generated by Django 5.0.14 on 2025-09-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0005_attachmentlimitconfiguration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="offlinesyncbatch",
            name="error_notification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Не отправлено"),
                    ("sent", "Отправлено"),
                    ("skipped", "Нет получателей"),
                ],
                default="pending",
                help_text="Результат отправки email-уведомления об ошибке.",
                max_length=20,
                verbose_name="Статус уведомления",
            ),
        ),
        migrations.AddField(
            model_name="offlinesyncbatch",
            name="error_notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда администраторам было отправлено уведомление об ошибке.",
                null=True,
                verbose_name="Уведомление отправлено",
            ),
        ),
    ]
